version: 2.1 # Use 2.1 to enable using orbs and other features.

# Declare the orbs that we'll use in our config.
orbs:
  ruby: circleci/ruby@1.0
  rubocop: hanachin/rubocop@0.0.6

jobs:
  test:
    parallelism: 1
    docker:
      - image: cimg/ruby:2.7-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: Run tests
          command: bundle exec rspec -fd

workflows:
  version: 2
  checks:
    jobs:
      - rubocop/rubocop
      - test
